import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { Limits } from "./deckcheck.ts";

// Card limits of the TCG list in force on 2005-04-01, the Goat format: passcode to copies allowed (0 forbidden, 1 limited, 2 semi-limited).
// Generated by `pnpm lflist`: the image has no YGOJSON, the server reads this file only.
const limits: Record<string, number> = JSON.parse(readFileSync(join(import.meta.dirname, "..", "data", "goat-2005-04.json"), "utf-8"));
export const GOAT: Limits = new Map(Object.entries(limits).map(([code, max]) => [Number(code), max]));
