import { readFileSync } from "node:fs";
import { join } from "node:path";
import { OBELISK_ANIME, RA_ANIME, SLIFER_ANIME } from "./decks.ts";

export const RARITIES = new Set(["common", "shortprint", "rare", "super", "ultra", "ultimate", "secret"]);

// One entry per printing: an Ultimate Rare variant repeats the passcode with its own rarity.
export type CardSet = { code: string; name: string; date: string; cards: { code: number; rarity: string }[] };

// Generated by `pnpm import-sets`.
export const SETS: CardSet[] = JSON.parse(readFileSync(join(import.meta.dirname, "..", "data", "sets.json"), "utf-8"));

// Unofficial (anime) cards allowed outside boosters, unlocked by Story mode.
export const WHITELIST: ReadonlySet<number> = new Set([OBELISK_ANIME, SLIFER_ANIME, RA_ANIME]);

export const POOL: ReadonlySet<number> = new Set([...SETS.flatMap((set) => set.cards.map((card) => card.code)), ...WHITELIST]);

export const isAllowed = (code: number) => POOL.has(code);
