import { readFileSync } from "node:fs";
import { join } from "node:path";
import { OBELISK_ANIME, RA_ANIME, SLIFER_ANIME } from "./decks.ts";

export const RARITIES = new Set(["common", "shortprint", "rare", "super", "ultra", "ultimate", "secret"]);

export type Printing = { code: number; rarity: string };
// YGOJSON pool slot: each rarity group has a 1:chance odd, the group without chance takes the rest.
export type Slot = { qty?: number; proportionate?: boolean; rarity: { rarities: string[]; chance?: number }[] };
// One entry per printing: an Ultimate Rare variant repeats the passcode with its own rarity.
// Boosters have slots, starter decks have none.
export type CardSet = { code: string; name: string; date: string; slots?: Slot[]; cards: Printing[] };

// Cards that freeze the engine, out of every booster and deck (found by `pnpm audit-cartes`, which still plays them by passcode).
// Last Turn (28566710): its forced attack, when the opponent answers an attack with it, never returns from the End Phase.
export const BROKEN: ReadonlySet<number> = new Set([28566710]);

// Generated by `pnpm import-sets`.
const printed: CardSet[] = JSON.parse(readFileSync(join(import.meta.dirname, "..", "data", "sets.json"), "utf-8"));
export const SETS: CardSet[] = printed.map((set) => ({ ...set, cards: set.cards.filter((card) => !BROKEN.has(card.code)) }));

// Unofficial (anime) cards allowed outside boosters, unlocked by Story mode.
export const WHITELIST: ReadonlySet<number> = new Set([OBELISK_ANIME, SLIFER_ANIME, RA_ANIME]);

export const POOL: ReadonlySet<number> = new Set([...SETS.flatMap((set) => set.cards.map((card) => card.code)), ...WHITELIST]);

export const isAllowed = (code: number) => POOL.has(code);
